openapi: 3.0.3
info:
  title: Sosalud API
  description: Esta API permite la auditoria de cuentas medicas
  version: 1.0.0

servers:
  - url: http://159.223.194.40:8081/api

tags:
  - name: autenticacion
    description: Tareas de creaci贸n y autenticacion de usuarios
  - name: validador
    description: Rutas del validador de RIPS

paths:
  /registrar:
    post:
      tags:
        - autenticacion
      summary: Registrar usuarios nuevos
      description: Registrar usuarios nuevos
      operationId: crearUsuario
      requestBody:
        description: Crear un nuevo usuario
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrearUsuario"
        required: true
      responses:
        "201":
          description: Usuario creado correctamente
        "400":
          description: Error en la informacion
  /login:
    post:
      tags:
        - autenticacion
      summary: Permite iniciar sesi贸n al usuario
      description: Permite iniciar sesi贸n al usuario
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuario"
      responses:
        "201":
          description: Obtener credenciales del inicio de sesi贸n
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
        "400":
          description: Error en los datos enviados
        "404":
          description: Credenciales invalidas

components:
  schemas:
    CrearUsuario:
      type: object
      properties:
        nombre:
          type: string
          example: "Nombre"
        nombreUsuario:
          type: string
          example: "nombreUsuario"
        email:
          type: string
          example: "email@example.com"

    Usuario:
      type: object
      properties:
        nombreUsuario:
          type: string
          example: "email@example.com | nombreUsuario"
        password:
          type: string

    Login:
      type: object
      properties:
        token:
          type: string
        usuario:
          type: object
          properties:
            id:
              type: integer
            nombreUsuario:
              type: string
              example: "nombreUsuario"

  parameters:
    token:
      name: token
      in: header
      description: Token para autenticar el usuario
      required: true
      schema:
        type: string
